const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const SOURCES = [
['E0','2627'],['SP1','2627'],['I1','2627'],['D1','2627'],['F1','2627'],
['E0','2526'],['SP1','2526'],['I1','2526'],['D1','2526'],['F1','2526'],
['E0','2425'],['SP1','2425'],['I1','2425'],['D1','2425'],['F1','2425']
] as const;
function parseCsv(text:string){const rs:string[][]=[];let r:string[]=[],c='',q=false;for(let i=0;i<text.length;i++){const x=text[i];if(x==='"'){if(q&&text[i+1]==='"'){c+='"';i++}else q=!q}else if(x===','&&!q){r.push(c);c=''}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&text[i+1]==='\n')i++;r.push(c);c='';if(r.some(Boolean))rs.push(r);r=[]}else c+=x}if(c||r.length){r.push(c);rs.push(r)}if(!rs.length)return[];const h=rs[0].map(x=>x.trim());return rs.slice(1).map(v=>Object.fromEntries(h.map((k,i)=>[k,(v[i]??'').trim()])))}
const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?Math.trunc(n):null};
function date(v:string){if(!v)return null;const p=v.split('/');if(p.length===3){let[d,m,y]=p;if(y.length===2)y='20'+y;return`${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`}return null}
const headers=(extra:any={})=>({apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':'application/json',...extra});
async function rest(path:string,init:RequestInit={}){const res=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...headers(),...(init.headers||{})}});if(!res.ok)throw new Error(`${res.status} ${await res.text()}`);const t=await res.text();return t?JSON.parse(t):null}
async function upsert(table:string,rows:any[],conflict:string){for(let i=0;i<rows.length;i+=300)await rest(`${table}?on_conflict=${encodeURIComponent(conflict)}`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows.slice(i,i+300))})}
async function leagueRows(code:string){const all:any[]=[];for(let off=0;;off+=1000){const b=await rest(`football_match_history?select=*&league_code=eq.${code}&order=match_date.asc&limit=1000&offset=${off}`);all.push(...b);if(b.length<1000)break}return all}
const expected=(a:number,b:number)=>1/(1+10**((b-a)/400));
const points=(gf:number,ga:number)=>gf>ga?3:gf===ga?1:0;
async function recompute(code:string){const ms=await leagueRows(code),elo=new Map<string,number>(),logs=new Map<string,any[]>();for(const m of ms){if(m.home_goals==null||m.away_goals==null)continue;const h=m.home_team,a=m.away_team,eh=elo.get(h)??1500,ea=elo.get(a)??1500,e=expected(eh+65,ea),act=m.home_goals>m.away_goals?1:m.home_goals===m.away_goals?.5:0,diff=Math.abs(m.home_goals-m.away_goals),mult=diff<=1?1:diff===2?1.5:(11+diff)/8,delta=24*mult*(act-e);elo.set(h,eh+delta);elo.set(a,ea-delta);const base={date:m.match_date,home:h,away:a};const lh=logs.get(h)??[];lh.push({...base,side:'H',gf:m.home_goals,ga:m.away_goals,pts:points(m.home_goals,m.away_goals),sf:m.home_shots,sa:m.away_shots,sotf:m.home_shots_target,sota:m.away_shots_target});logs.set(h,lh);const la=logs.get(a)??[];la.push({...base,side:'A',gf:m.away_goals,ga:m.home_goals,pts:points(m.away_goals,m.home_goals),sf:m.away_shots,sa:m.home_shots,sotf:m.away_shots_target,sota:m.home_shots_target});logs.set(a,la)}const recentAll=[...logs.values()].flatMap(v=>v.slice(-20)),lgAvg=recentAll.length?recentAll.reduce((s,x)=>s+x.gf,0)/recentAll.length:1.3,out:any[]=[];for(const[team,arr]of logs){const recent=arr.slice(-20),last5=arr.slice(-5),home=recent.filter(x=>x.side==='H'),away=recent.filter(x=>x.side==='A'),sum=(xs:any[],k:string)=>xs.reduce((s,x)=>s+(Number(x[k])||0),0),avg=(xs:any[],k:string)=>xs.length?sum(xs,k)/xs.length:lgAvg,w=arr.filter(x=>x.pts===3).length,d=arr.filter(x=>x.pts===1).length;out.push({league_code:code,team_name:team,elo:+(elo.get(team)??1500).toFixed(2),matches:arr.length,wins:w,draws:d,losses:arr.length-w-d,goals_for:sum(arr,'gf'),goals_against:sum(arr,'ga'),shots_for:sum(arr,'sf'),shots_against:sum(arr,'sa'),shots_target_for:sum(arr,'sotf'),shots_target_against:sum(arr,'sota'),form_points:+((sum(last5,'pts')/Math.max(1,last5.length*3))*100).toFixed(2),attack_strength:+(avg(recent,'gf')/Math.max(.2,lgAvg)).toFixed(4),defense_strength:+(avg(recent,'ga')/Math.max(.2,lgAvg)).toFixed(4),home_attack_strength:+(avg(home,'gf')/Math.max(.2,lgAvg)).toFixed(4),home_defense_strength:+(avg(home,'ga')/Math.max(.2,lgAvg)).toFixed(4),away_attack_strength:+(avg(away,'gf')/Math.max(.2,lgAvg)).toFixed(4),away_defense_strength:+(avg(away,'ga')/Math.max(.2,lgAvg)).toFixed(4),last_matches:last5.slice().reverse().map(x=>({date:x.date,opponent:x.side==='H'?x.away:x.home,side:x.side,gf:x.gf,ga:x.ga,pts:x.pts})),data_points:recent.length,updated_at:new Date().toISOString()})}await upsert('football_team_ratings',out,'league_code,team_name');return out.length}
Deno.serve(async()=>{const recent=await rest('model_refresh_runs?select=started_at,status&model_domain=eq.football&status=eq.success&order=started_at.desc&limit=1');if(recent?.[0]&&Date.now()-new Date(recent[0].started_at).getTime()<20*60*1000)return Response.json({ok:true,skipped:'recent_refresh'});const run=await rest('model_refresh_runs',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({model_domain:'football',source:'football-data.co.uk',status:'running'})}),id=run[0].id;let received=0,upserted=0,ratingsUpdated=0;try{for(const[league,season]of SOURCES){const url=`https://www.football-data.co.uk/mmz4281/${season}/${league}.csv`,res=await fetch(url,{headers:{'User-Agent':'Predictive/1.0'}});if(!res.ok)throw new Error(`${url} ${res.status}`);const parsed=parseCsv(await res.text()),rows=parsed.map((x:any)=>{const dt=date(x.Date);if(!dt||!x.HomeTeam||!x.AwayTeam||x.FTHG===''||x.FTAG==='')return null;return{source:'football-data.co.uk',league_code:league,season,match_date:dt,home_team:x.HomeTeam,away_team:x.AwayTeam,home_goals:num(x.FTHG),away_goals:num(x.FTAG),result:x.FTR||null,home_shots:num(x.HS),away_shots:num(x.AS),home_shots_target:num(x.HST),away_shots_target:num(x.AST),home_corners:num(x.HC),away_corners:num(x.AC),home_yellow:num(x.HY),away_yellow:num(x.AY),home_red:num(x.HR),away_red:num(x.AR),raw:{Div:x.Div,HTHG:x.HTHG,HTAG:x.HTAG,HTR:x.HTR}}}).filter(Boolean);received+=parsed.length;upserted+=rows.length;await upsert('football_match_history',rows,'source,league_code,season,match_date,home_team,away_team')}for(const c of['E0','SP1','I1','D1','F1'])ratingsUpdated+=await recompute(c);await rest(`model_refresh_runs?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:'success',records_received:received,records_upserted:upserted,ratings_updated:ratingsUpdated,finished_at:new Date().toISOString(),details:{leagues:['E0','SP1','I1','D1','F1'],seasons:['2425','2526','2627']}})});return Response.json({ok:true,received,upserted,ratingsUpdated})}catch(e){await rest(`model_refresh_runs?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:'error',error_message:String(e),finished_at:new Date().toISOString()})}).catch(()=>{});return Response.json({ok:false,error:String(e)},{status:500})}});