-- GoalMind initial database contract.
-- This file is NOT applied to any Supabase project yet.
-- All tables in the exposed public schema enable RLS.

create extension if not exists pgcrypto;

create type public.user_role as enum ('student', 'teacher', 'admin');
create type public.game_status as enum ('draft', 'lobby', 'live', 'finished', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'student',
  display_name text not null,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.question_banks (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  subject text not null,
  grade smallint,
  created_at timestamptz not null default now()
);

create table public.questions (
  id uuid primary key default gen_random_uuid(),
  bank_id uuid not null references public.question_banks(id) on delete cascade,
  prompt text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_answer smallint not null check (correct_answer between 0 and 3),
  explanation text not null default '',
  component text,
  topic text,
  difficulty text not null,
  image_url text,
  created_at timestamptz not null default now()
);

create table public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  bank_id uuid references public.question_banks(id) on delete set null,
  join_code text not null unique,
  status public.game_status not null default 'draft',
  seconds_per_question smallint not null default 8 check (seconds_per_question between 3 and 60),
  question_count smallint not null default 10 check (question_count between 1 and 100),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create table public.game_participants (
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  score integer not null default 0,
  primary key (session_id, user_id)
);

create table public.answers (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  question_id uuid not null references public.questions(id) on delete cascade,
  selected_answer smallint check (selected_answer between 0 and 3),
  correct boolean not null,
  elapsed_ms integer not null check (elapsed_ms >= 0),
  points integer not null default 0 check (points >= 0),
  timed_out boolean not null default false,
  answered_at timestamptz not null default now(),
  unique (session_id, user_id, question_id)
);

alter table public.profiles enable row level security;
alter table public.question_banks enable row level security;
alter table public.questions enable row level security;
alter table public.game_sessions enable row level security;
alter table public.game_participants enable row level security;
alter table public.answers enable row level security;

create policy "profiles read own" on public.profiles
for select to authenticated
using ((select auth.uid()) = id);

create policy "profiles update own" on public.profiles
for update to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "teachers manage own banks" on public.question_banks
for all to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create policy "bank owners manage questions" on public.questions
for all to authenticated
using (exists (
  select 1 from public.question_banks b
  where b.id = bank_id and b.owner_id = (select auth.uid())
))
with check (exists (
  select 1 from public.question_banks b
  where b.id = bank_id and b.owner_id = (select auth.uid())
));

create policy "teachers manage own sessions" on public.game_sessions
for all to authenticated
using ((select auth.uid()) = teacher_id)
with check ((select auth.uid()) = teacher_id);

create policy "participants read own participation" on public.game_participants
for select to authenticated
using ((select auth.uid()) = user_id);

create policy "participants insert self" on public.game_participants
for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "students read own answers" on public.answers
for select to authenticated
using ((select auth.uid()) = user_id);

create policy "students insert own answers" on public.answers
for insert to authenticated
with check ((select auth.uid()) = user_id);
